redoing: namespace get_template_part action hook
GaryJones/Gamajo-Template-Loader pull request #29
Opened 2017-01-30 22:53 UTC by cliffordp

by adding a new action hook instead of replacing the existing one

replacement for the pull request that _was_ at https://github.com/GaryJones/Gamajo-Template-Loader/pull/25

2017-02-24 11:04 UTC, GaryJones requested changes

2017-02-24 11:04 UTC, GaryJones commented on class-gamajo-template-loader.php
> +			do_action( 'get_template_part_' . $this->filter_prefix . '_' . $slug, $slug, $name );
I think it should be:
```php
do_action( $this->filter_prefix . '_get_template_part_' . $slug, $slug, $name );
```
as that's how the `filter_prefix` property is used in two existing filters.

2017-03-15 21:27 UTC, GaryJones approved these changes

2017-03-15 21:28 UTC, merged

2017-03-15 21:28 UTC, GaryJones commented
Thank you :-)

2017-03-24 16:43 UTC, cliffordp commented
Thank _you_!

Also wanted to remind you of the version bump in both the file's comments and the tag on github.

2017-03-24 17:30 UTC, GaryJones commented
@cliffordp Thanks for the nudge :-)

https://github.com/GaryJones/Gamajo-Template-Loader/releases/tag/1.3.0